Made changes so that super admin will be able to search for review managers using their email addresses
bcgov/HOUS-permit-portal pull request #795
Opened 2024-11-27 03:10 UTC by mrsasi7994

Previously Super Admin Can't able to manager Review Managers using their email Addresses. Now made changes so that As a Super Admin, they can search Review Managers using their email.

2024-11-27 04:08 UTC, bkmaibach commented
This code would let unauthenticated users to check if any email is associated with review managers on a jurisdiction. I'm not sure that is a wise thing to allow. Is there some specific reason we are pursuing this feature?

2024-11-27 04:17 UTC, bkmaibach requested changes
Jurisdiction search is a public unauthenticated endpoint, and associated review managers is not public data. If this feature is absolutely necessary, please find a way to prevent the public from uncovering private information.

2024-11-27 20:30 UTC, bkmaibach requested changes
Please:

- Use role checking methods where appropriate (.super_admin? etc)
- Handle the case of regional review managers
- apply syntax_tree formatting (see README)

2024-11-27 20:53 UTC, sunto commented on app/models/jurisdiction.rb
> +  SEARCH_DATA_FIELDS = %i[qualified_name reverse_qualified_name regional_district_name name type updated_at review_managers_size reviewers_size permit_applications_size user_ids submission_inbox_set_
I would leave out updated_at and created_at

2024-11-28 17:23 UTC, sunto approved these changes

2024-11-28 20:04 UTC, guri-dev approved these changes

2024-11-29 21:35 UTC, bkmaibach approved these changes
Nicely done

2024-12-03 18:51 UTC, bkmaibach requested changes

2024-12-03 18:51 UTC, bkmaibach commented on app/models/jurisdiction.rb
> +      regional_review_manager_emails: regional_review_manager_emails
This might be better if they were the same field, like manager_emails or something

2024-12-04 22:31 UTC, bkmaibach approved these changes

2024-12-05 18:37 UTC, merged